### ISSUE TITLE
Feed renders no items

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/bogan#1]
```
$ bundle exec ruby scraper.rb 
Saving page 1 of 0
/home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/atdisplanningalertsfeed-ce20de6801cf/lib/atdisplanningalertsfeed.rb:22:in `save_page': undefined method `current' for nil:NilClass (NoMethodError)
    from /home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/atdisplanningalertsfeed-ce20de6801cf/lib/atdisplanningalertsfeed.rb:17:in `save'
    from scraper.rb:6:in `<main>'
```

Because 
http://datracker.bogan.nsw.gov.au:81/atdis/1.0/applications.json produces

```
{"response":[],"count":0,"pagination":{"previous":null,"next":2,"current":1,"per_page":0,"count":198,"pages":0}}
```

There are however at least some records:
http://datracker.bogan.nsw.gov.au:81/Application/AdvancedSearchResult?DateFrom=1%2f03%2f2016&DateTo=23%2f03%2f2016&DateType=1&RemoveUndeterminedApplications=False&ApplicationType=&ShowOutstandingApplications=False&ShowExhibitedApplications=False&IncludeDocuments=False

**Comment by CloCkWeRX** [comment]
```
Subject: Problem report: ATDIS (development applications tracker) feed
To: admin@bogan.nsw.gov.au

Hi,
You may wish to forward this one on to your IT department or product vendor.

You have a number of development applications listed via the web user interface of your tracking software; but none are showing up in the relevant data feed:

http://datracker.bogan.nsw.gov.au:81/atdis/1.0/applications.json

produces
{"response":[],"count":0,"pagination":{"previous":null,"next":2,"current":1,"per_page":0,"count":198,"pages":0}}

... which is a little contradictory. I would have expected to be able to see applications like DA 2016/5 for example.


This data feed is particularly useful for things like planningalerts.org.au, a non profit website aimed at making it easier for residents to engage in the planning process - it'd be really great if this turns out to be a simple fix; as I can add in the feed there.
```

**Comment by CloCkWeRX** [comment]
Well, the bug is fixed now:

```
$ bundle exec ruby scraper.rb
W, [2016-04-04T12:10:30.967395 #10063]  WARN -- : No/invalid pagination, assuming no records/aborting
```

... but its not really suitable to add yet.

**Comment by CloCkWeRX** [comment]
Added in via https://morph.io/planningalerts-scrapers/bogan and will play the waiting game to see if there is content
